darly/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import patterns, url
from darly import views

urlpatterns = [
    url(r'^$', views.DarlyPhotoListView.as_view(), name='darly_photo_view_page'),
]

fromleaf/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^', include('fromleaf_opening.urls', namespace='opening')),
    url(r'^aboutme/', include('fromleaf_aboutme.urls', namespace='aboutme')),
    url(r'^myskill/', include('fromleaf_myskill.urls', namespace='myskill')),
    url(r'^career/', include('fromleaf_career.urls', namespace='career')),
    url(r'^playing/', include('fromleaf_playing.urls', namespace='playing')),
    url(r'^contactme/', include('fromleaf_contactme.urls', namespace='contactme')),
    url(r'^admin/', admin.site.urls),
]


# CHECK: 개발용인데, STATIC 경로가 있어야 하나? Azure에서 없으면 못읽으려나??
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # While I'm developing my site, Media files are saved on "/app_name/media/location".  
    # If I want to laod my media files, I have to use this code.
    urlpatterns += static(r'^(?P<path>.*)$', document_root=settings.MEDIA_ROOT)

fromleaf_career/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import patterns, url

from fromleaf_career import views

urlpatterns = [
    url(r'^$', views.CareerView.as_view(), name='main'),
    url(r'^company_detail/(?P<pk>\d+)/$', views.CompanyDetailView.as_view(), name='company_detail')
]

fromleaf_career/models.py
from __future__ import unicode_literals
import os.path
from unidecode import unidecode

from django.db import models

from fromleaf_common.models.page import PageContainer
from fromleaf_common.models.user import MemberInfo

def get_upload_to(instance, filename):
    # Dumb proxy to instance method.
    return instance.get_upload_to(filename)

class CareerPage(models.Model):
    
    def __init__(self, *args, **kwargs):
        super(CareerPage, self).__init__(*args, **kwargs)
    
    def __unicode__(self):  # __str__ on Python3
        return self.name 
    
    name = 'Career Page'
    description = '그 동안 다년던 회사에 대한 설명과 제가 참여했던 프로젝트 및 개발에 대한 내용을 정리했습니다.'    
    page_container = models.OneToOneField(
                              PageContainer,
                              on_delete=models.CASCADE,
                              null=True
                              )
    
    created_at = models.DateTimeField(auto_now_add=True)
    
    
class Company(models.Model):
    def get_upload_to(self, filename):
        folder_name = 'photos/company/'
        filename = self.company_image.field.storage.get_valid_name(filename)

        # do a unidecode in the filename and then
        # replace non-ascii characters in filename with _ , to sidestep issues with filesystem encoding
        filename = "".join((i if ord(i) < 128 else '_') for i in unidecode(filename))

        # Truncate filename so it fits in the 100 character limit
        # https://code.djangoproject.com/ticket/9893
        while len(os.path.join(folder_name, filename)) >= 95:
            prefix, dot, extension = filename.rpartition('.')
            filename = prefix[:-1] + dot + extension
        
        return os.path.join(folder_name, filename) 
    
    def __init__(self, *args, **kwargs):
        super(Company, self).__init__(*args, **kwargs)
    
    def __unicode__(self):  # __str__ on Python3
        return self.name
    
    name = models.CharField(max_length=200)
    started_date = models.DateField()
    finished_date = models.DateField(null=True)
    simple_description = models.CharField(max_length=300, null=True)
    description = models.CharField(max_length=400, null=True)
    company_image = models.ImageField(upload_to=get_upload_to,
                                      default='/media/photos/default/no_image.png', 
                                      null=True
                                      )
    created_at = models.DateTimeField(auto_now_add=True)
    
    
    member_info = models.ForeignKey(
                              MemberInfo,
                              on_delete=models.CASCADE,
                              null=True
                              )
    career_page = models.ForeignKey(
                              CareerPage,
                              on_delete=models.CASCADE,
                              null=True
                              )

class Project(models.Model):
    
    def __init__(self, *args, **kwargs):
        super(Project, self).__init__(*args, **kwargs)
    
    def __unicode__(self):  # __str__ on Python3
        return self.title
    
    def get_thumnail_upload_to(self, filename):
        folder_name = 'photos/project/'
        filename = self.architecture_image.field.storage.get_valid_name(filename)

        # do a unidecode in the filename and then
        # replace non-ascii characters in filename with _ , to sidestep issues with filesystem encoding
        filename = "".join((i if ord(i) < 128 else '_') for i in unidecode(filename))

        # Truncate filename so it fits in the 100 character limit
        # https://code.djangoproject.com/ticket/9893
        while len(os.path.join(folder_name, filename)) >= 95:
            prefix, dot, extension = filename.rpartition('.')
            filename = prefix[:-1] + dot + extension
        
        return os.path.join(folder_name, filename)
    
    def get_architecture_upload_to(self, filename):
        folder_name = 'photos/architecture/'
        filename = self.architecture_image.field.storage.get_valid_name(filename)

        # do a unidecode in the filename and then
        # replace non-ascii characters in filename with _ , to sidestep issues with filesystem encoding
        filename = "".join((i if ord(i) < 128 else '_') for i in unidecode(filename))

        # Truncate filename so it fits in the 100 character limit
        # https://code.djangoproject.com/ticket/9893
        while len(os.path.join(folder_name, filename)) >= 95:
            prefix, dot, extension = filename.rpartition('.')
            filename = prefix[:-1] + dot + extension
        
        return os.path.join(folder_name, filename) 
    
    title = models.CharField(max_length=200)
    simple_description = models.CharField(max_length=300, null=True)
    duty_description = models.CharField(max_length=300, null=True)
    started_date = models.DateField()
    finished_date = models.DateField(null=True)
    language = models.CharField(max_length=200, null=True)
    system = models.CharField(max_length=200, null=True)
    framework = models.CharField(max_length=200, null=True)
    database = models.CharField(max_length=200, null=True)
    thumnail_image = models.ImageField(
                                           upload_to=get_thumnail_upload_to, 
                                           default='/media/photos/default/no_image.png',
                                           null=True
                                           )
    architecture_image = models.ImageField(
                                           upload_to=get_architecture_upload_to, 
                                           default='/media/photos/default/no_image.png',
                                           null=True
                                           )
    architecture_describe = models.CharField(max_length=400, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    
    company = models.ForeignKey(
                              Company,
                              on_delete=models.CASCADE,
                              )

fromleaf_career/views.py
from django.shortcuts import render
from django.conf import settings

from fromleaf_common.utils import database as db
from fromleaf_common.utils.database import UserData, CompanyData
from fromleaf_common.views import CommonListView, CommonDetailView
from fromleaf_career.models import Company, Project


class CareerView(CommonListView):
    
    template_name = 'fromleaf_career/career.html'
    context_object_name = 'company_list'
    
    def get_queryset(self):
        user_data = UserData(settings.USER_EMAIL)
        return Company.objects.filter(member_info=user_data.get_member_info())
    
    def get_context_data(self, **kwargs):
        context = super(CareerView, self).get_context_data(**kwargs)
        
        return context
        

class CompanyDetailView(CommonDetailView):
    template_name = 'fromleaf_career/company.html'
    model = Company
    context_object_name = 'company'
 
    def get_context_data(self, **kwargs):
        context = super(CompanyDetailView, self).get_context_data(**kwargs)
        company_data = CompanyData(settings.USER_EMAIL)
        company = self.get_object()
        context['project_list'] = company_data.get_project_list_of_company(company)
        return context

fromleaf_career/templates/fromleaf_career/career.html
{% extends "base.html" %}

<head>
    <title>{% block title %}History{% endblock title %}</title>
</head>


{% block page-information %}
<div class="jumbotron">
    <h1>{{ page_info.name }}</h1>
    <p>{{ page_info.description }}</p>
</div><!--/.jumbotron -->

<div class="error_message">
    {% if error_message %}
    <ul>
        <li>{{error_message}}</li>
    </ul>
    {% endif %}
</div>
{% endblock page-information %}

{% block blog-main %}
<div class="blog-post">	
	<div class="col-md-15">
		{% for company in company_list %}
		<hr class="featurette-divider">
		<div class="row company">
			<div class="col-md-8">
				<h2 class="company-heading">
					{{ company.name }}
				</h2>
				<p>{{ company.started_date }} ~ {{ company.finished_date }}</p>
				<p><span class="text-muted">{{ company.simple_description }}</span><p>
				<p><a class="btn btn-primary" href="{% url 'career:company_detail' company.id %}" role="button">View Detail &raquo;</a></p>
			</div>
			<div class="col-md-4">
				<a href="{% url 'career:company_detail' company.id %}" role="button"><img class="featurette-image img-responsive center-block"
					data-src="holder.js/500x500/auto"
					src="{{ company.company_image.url }}"
					alt="Generic placeholder image"></a>
			</div>
		</div><!-- /.row company -->
		{% empty %}
		<li>Sorry, no company in this list.</li>
		{% endfor %}
	</div><!--/.col-md-15-->
</div><!-- /.blog-post -->
{% endblock blog-main %}

fromleaf_career/templates/fromleaf_career/company.html
{% extends "base.html" %}

<head>
<title>{% block title %}History{% endblock title %}</title>
</head>


{% block page-information %}
<div class="jumbotron">
    <h1>{{ page_info.name }}</h1>
    <p>{{ page_info.description }}</p>
</div><!--/.jumbotron -->

<div class="error_message">
    {% if error_message %}
    <ul>
        <li>{{error_message}}</li>
    </ul>
    {% endif %}
</div>
{% endblock page-information %}

{% block blog-main %}

<div class="blog-post">
	<div class="col-md-15">
		<hr class="featurette-divider">
		<div class="row company">
			<div class="col-md-8">
				<h2 class="company-heading">{{company.name}}</h2>
				<p>{{company.started_date}} ~ {{company.finished_date}}</p>
				<p>
					<span class="text-muted">{{company.simple_description}}</span>
				</p>
				<p>{{company.description}}</p>
			</div>
			<div class="col-md-4">
				<img class="featurette-image img-responsive center-block"
					data-src="holder.js/500x500/auto"
					src="{{company.company_image.url}}" alt="Generic placeholder image">
			</div>
		</div>
		<!-- /.row company -->

		<hr class="featurette-divider">
		<div class="row">
			{% for project in project_list %}
			<div class="col-md-4">
				<img class="img-circle" src="{{project.thumnail_image.url}}"
					alt="Generic placeholder image" width="140" height="140">
				<h5>{{project.title}}</h5>
				{% if project.finished_date %}
				<p>{{project.started_date}} ~ {{project.finished_date}}</p>
				{% else %}
				<p>{{project.started_date}}</p>
				{% endif %}
				<p>{{project.simple_description}}</p>
				<p>
					<!-- Button trigger modal -->
					<button type="button" class="btn btn-primary" data-toggle="modal"
						data-target="#myModal_{{project.pk}}">View Detail &raquo;</button>
				</p>
				
				<!-- Modal -->
				<div class="modal fade bs-example-modal-lg"
					id="myModal_{{project.pk}}" tabindex="-1" role="dialog"
					aria-labelledby="myModalLabel" aria-hidden="true">
					<div class="modal-dialog modal-lg">
						<div class="modal-content">
							<div class="modal-header">
								<button type="button" class="close" data-dismiss="modal"
									aria-label="Close">
									<span aria-hidden="true">&times;</span>
								</button>
								<h4 class="modal-title">{{project.title}}</h4>
								{% if project.finished_date %}
								<p>{{project.started_date}} ~ {{project.finished_date}}</p>
								{% else %}
								<p>{{project.started_date}}</p>
								{% endif %}
							</div>
							<div class="modal-body">
								<div class="row featurette">
									<div class="col-md-7 col-md-push-5">
										<h4 class="featurette-heading">Project Summary</h4>
										{% if project.simple_description %}
										<li>{{project.simple_description}}</li>
										{% endif %} 
										{% if project.duty_description %}
										<li>Duty : {{project.duty_description}}</li> 
										{% endif %}
										<hr class="featurette-divider">
										<p>
										<h4 class="featurette-heading">Project System</h4>
										</p>
										{% if project.language %}
										<li>Language: {{project.language}}</li> 
										{% endif %} 
										{% if project.system %}
										<li>System: {{project.system}}</li> 
										{% endif %} 
										{% if project.framework %}
										<li>Framework: {{project.framework}}</li> 
										{% endif %}
									</div>
									{% if project.architecture_image.url != None %}
									<div class="col-md-5 col-md-pull-7">
										<p>
											<img class="featurette-image img-responsive center-block"
												data-src="holder.js/500x500/auto"
												src="{{project.architecture_image.url}}"
												alt="Architecture image">
										</p>
										{% if project.architecture_describe %}
										{{project.architecture_describe}}
										{% endif %}
									</div>
									{% else %}
									<div class="col-md-5 col-md-pull-7">
										<p>
											<img class="featurette-image img-responsive center-block"
												data-src="holder.js/500x500/auto"
												src="/media/photos/default/no_image.png"
												alt="Architecture image">
										</p>
										{% if project.architecture_describe %}
										{{project.architecture_describe}}
										{% endif %}
									</div>
									{% endif %}
								</div>
							</div>
							<!-- /.modal-body -->
							<div class="modal-footer">
								<button type="button" class="btn btn-default"
									data-dismiss="modal">Close</button>
							</div>
						</div>
						<!-- /.modal-content -->
					</div>
					<!-- /.modal-dialog -->
				</div>
				<!-- /.modal -->
				</div>
				<!-- /.col-lg-4 -->
			{% empty %}
			<li>Project list is empty</li>
			{% endfor %}
		</div>
		<!-- /.row -->
	</div>
	<!--/.col-md-15-->
</div>
<!-- /.blog-post -->
{% endblock blog-main %}